version: '3.9'
services:  
  webapi:
    image: nicolasgranata/todosample
    build:
      context: .
      dockerfile: src/TodoSample.WebApi/Dockerfile
    ports:
        - 63500:80
        - 63501:443
    environment:
        - ASPNETCORE_ENVIRONMENT=Development